export const CATS = {
  website: {
    icon: "🌐", label: "Website", color: "#3b82f6",
    desc: "Landing pages, portfolios, blogs, corporate sites",
    examples: [
      { emoji: "👤", label: "Portfolio", text: "create portfolio website for data scientist" },
      { emoji: "🚀", label: "Startup Landing", text: "create startup landing page for AI SaaS company" },
      { emoji: "🍕", label: "Restaurant", text: "create restaurant website with menu and online booking" },
      { emoji: "📰", label: "Blog", text: "create tech blog website with dark theme" },
      { emoji: "🏢", label: "Corporate", text: "create corporate website for IT company" },
      { emoji: "🎨", label: "Creative Agency", text: "create creative design agency website" },
      { emoji: "💚", label: "NGO", text: "create NGO website for education charity organization" },
      { emoji: "🛍️", label: "Product Page", text: "create product landing page for mobile app" },
    ],
  },
  mobile: {
    icon: "📱", label: "Mobile App", color: "#8b5cf6",
    desc: "Python Kivy / BeeWare native mobile apps with live preview",
    examples: [
      { emoji: "🔢", label: "Calculator", text: "create scientific calculator app with history using Kivy" },
      { emoji: "🎯", label: "Number Guessing", text: "create number guessing game with score tracking" },
      { emoji: "📚", label: "Grade Tracker", text: "create student grade and CGPA calculator app" },
      { emoji: "💰", label: "Expense Tracker", text: "create personal expense tracker with charts using BeeWare" },
      { emoji: "📝", label: "Todo App", text: "create kanban todo app with SQLite using Kivy" },
      { emoji: "🏃", label: "Health Tracker", text: "create BMI and health tracker app with Kivy" },
      { emoji: "🎓", label: "Quiz App", text: "create Python quiz game with leaderboard using BeeWare" },
      { emoji: "📅", label: "Study Planner", text: "create student study planner with timetable using Kivy" },
    ],
  },
  design: {
    icon: "🎨", label: "Design Tool", color: "#ec4899",
    desc: "Photo editors, BG remover, Canva-like tools (OpenCV, Pillow)",
    examples: [
      { emoji: "🖼️", label: "Photo Editor", text: "create photo editor with Instagram-style filters" },
      { emoji: "✂️", label: "BG Remover", text: "create background remover tool with Replace background" },
      { emoji: "📢", label: "Banner Maker", text: "create social media banner maker with templates" },
      { emoji: "🎯", label: "Logo Maker", text: "create logo maker tool with shapes and fonts" },
      { emoji: "📸", label: "Thumbnail Maker", text: "create YouTube thumbnail maker with text overlay" },
      { emoji: "🎨", label: "Color Palette", text: "create color palette generator and picker tool" },
      { emoji: "✍️", label: "Text Effects", text: "create text effect designer with shadows and gradients" },
      { emoji: "📐", label: "Canva Clone", text: "create Canva-like design tool with drag and drop" },
    ],
  },
  ppt: {
    icon: "📊", label: "Slides / PPT", color: "#f59e0b",
    desc: "Auto-generate presentations (python-pptx, Marp, Reveal.js, Manim)",
    examples: [
      { emoji: "🤖", label: "AI Presentation", text: "create ppt presentation about artificial intelligence" },
      { emoji: "💼", label: "Startup Pitch", text: "create startup pitch deck for investor meeting" },
      { emoji: "📱", label: "Product Demo", text: "create product demo presentation for mobile app" },
      { emoji: "🎓", label: "Educational", text: "create educational slides about machine learning basics" },
      { emoji: "📊", label: "Sales Report", text: "create quarterly sales report presentation with charts" },
      { emoji: "🔬", label: "Research Paper", text: "create research paper presentation about climate change" },
      { emoji: "🏢", label: "Company Overview", text: "create company overview presentation for new employees" },
      { emoji: "🚀", label: "Project Proposal", text: "create project proposal presentation for client approval" },
    ],
  },
  game: {
    icon: "🎮", label: "Game", color: "#10b981",
    desc: "2D/3D browser games: Phaser, Three.js, PlayCanvas, Canvas API",
    examples: [
      { emoji: "🐍", label: "Snake Game", text: "create classic snake game with score and speed levels" },
      { emoji: "🧱", label: "Tetris", text: "create Tetris game with rotation and line clear effects" },
      { emoji: "♟️", label: "Chess", text: "create chess game with AI opponent and move validation" },
      { emoji: "🎲", label: "Ludo", text: "create Ludo board game with multiplayer dice rolls" },
      { emoji: "🔫", label: "Shooter", text: "create 2D zombie shooter game with Phaser" },
      { emoji: "🏃", label: "Platformer", text: "create side-scrolling platformer game with physics" },
      { emoji: "🧩", label: "Puzzle", text: "create sliding puzzle game with timer and moves counter" },
      { emoji: "🚀", label: "Space Invaders", text: "create space invaders game with power-ups and waves" },
    ],
  },
  ml: {
    icon: "🤖", label: "ML Project", color: "#6366f1",
    desc: "Full ML pipeline: data → model → prediction UI (Scikit/PyTorch/TF)",
    examples: [
      { emoji: "🏠", label: "House Price", text: "create house price prediction ML project with sklearn" },
      { emoji: "🎬", label: "Movie Recommender", text: "create movie recommendation system using collaborative filtering" },
      { emoji: "📧", label: "Spam Detector", text: "create email spam classifier using Naive Bayes" },
      { emoji: "📉", label: "Churn Prediction", text: "create customer churn prediction for telecom company" },
      { emoji: "💭", label: "Sentiment Analysis", text: "create sentiment analysis for product reviews using NLP" },
      { emoji: "💳", label: "Fraud Detection", text: "create credit card fraud detection using Random Forest" },
      { emoji: "🩺", label: "Disease Prediction", text: "create diabetes prediction ML project using SVM" },
      { emoji: "👥", label: "Customer Segments", text: "create customer segmentation using K-means clustering" },
    ],
  },
  ecommerce: {
    icon: "🛒", label: "E-Commerce", color: "#f97316",
    desc: "Full shopping sites: React + Node + MongoDB + Stripe/Razorpay",
    examples: [
      { emoji: "🛍️", label: "Flipkart Clone", text: "create flipkart-like ecommerce website for Indian market" },
      { emoji: "📦", label: "Amazon Clone", text: "create amazon-style multi-category shopping website" },
      { emoji: "👗", label: "Fashion Store", text: "create women fashion boutique with size selector" },
      { emoji: "💻", label: "Electronics Shop", text: "create electronics store for mobiles and laptops" },
      { emoji: "🌿", label: "Grocery Store", text: "create online grocery delivery store like BigBasket" },
      { emoji: "💄", label: "Beauty Store", text: "create beauty and cosmetics store like Nykaa" },
      { emoji: "📚", label: "Bookstore", text: "create online bookstore with genre filter" },
      { emoji: "👟", label: "Shoes Store", text: "create footwear store with size and brand filter" },
    ],
  },
  more: {
    icon: "⋯", label: "More Apps", color: "#64748b",
    desc: "Weather, quiz, chat, todo, portfolio & more",
    examples: [
      { emoji: "🌤️", label: "Weather App", text: "create weather app with 7-day forecast and maps" },
      { emoji: "❓", label: "Quiz App", text: "create general knowledge quiz app with timer and leaderboard" },
      { emoji: "💬", label: "Chat Messenger", text: "create WhatsApp-style chat messenger app" },
      { emoji: "✅", label: "Kanban Todo", text: "create Kanban board todo app with drag and drop" },
      { emoji: "👨‍💻", label: "Dev Portfolio", text: "create developer portfolio with projects and GitHub" },
      { emoji: "🍅", label: "Pomodoro Timer", text: "create Pomodoro productivity timer with task list" },
      { emoji: "📖", label: "Blog Site", text: "create blog website with article cards and search" },
      { emoji: "🔄", label: "Unit Converter", text: "create unit converter app with all measurement types" },
    ],
  },
};
